name: 'Issue Links'
on:
  pull_request:
    types: [opened]

jobs:
  issue-links:
    runs-on: ubuntu-latest
    steps:
    - uses: tkt-actions/add-issue-links@v1
      with:
        repo-token: '${{ secrets.GITHUB_TOKEN }}'
        branch-prefix: 'gh-'
        link-style: 'body'
        resolve: 'true'
